--
-- PostgreSQL database dump
--

-- Dumped from database version 13.20
-- Dumped by pg_dump version 16.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: rate_limits; Type: TABLE; Schema: mx; Owner: postgres
--

CREATE TABLE mx.rate_limits (
    id integer NOT NULL,
    domain character varying(255),
    "limit" integer
);


ALTER TABLE mx.rate_limits OWNER TO postgres;

--
-- Name: rate_limits_id_seq; Type: SEQUENCE; Schema: mx; Owner: postgres
--

ALTER TABLE mx.rate_limits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mx.rate_limits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: rate_limits; Type: TABLE DATA; Schema: mx; Owner: postgres
--

COPY mx.rate_limits (id, domain, "limit") FROM stdin;
1	leadtinfo.com	2
2	google.com	49
3	outlook.com	49
\.


--
-- Name: rate_limits_id_seq; Type: SEQUENCE SET; Schema: mx; Owner: postgres
--

SELECT pg_catalog.setval('mx.rate_limits_id_seq', 3, true);


--
-- Name: rate_limits rate_limits_domain_key; Type: CONSTRAINT; Schema: mx; Owner: postgres
--

ALTER TABLE ONLY mx.rate_limits
    ADD CONSTRAINT rate_limits_domain_key UNIQUE (domain);


--
-- Name: rate_limits rate_limits_pkey; Type: CONSTRAINT; Schema: mx; Owner: postgres
--

ALTER TABLE ONLY mx.rate_limits
    ADD CONSTRAINT rate_limits_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

