CREATE TABLE public.ranked_email (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email character varying(255) CONSTRAINT proper_email CHECK (check_email(email)),
    website character varying(2000),
    hdrurl varchar(2000),
    constraint pkey_track_uniq unique(email,content_url)
);

CREATE TABLE yp.yellow_pages (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    address character varying(255),
    city character varying(80),
    name character varying(255),
    phone character varying(255),
    state character varying(2),
    tags character varying(255),
    website character varying(2000),
    zip character varying(11),
    category varchar(255),
    did integer references domain(id)
);

/* 
did integer references domain(id),
*/

CREATE TABLE public.domain (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    domain varchar(255) unique
  );

create table whois_contact (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar(1024),
  organization varchar(1024) null,
  street varchar(1024),
  city varchar(1024),
  state varchar(1024),
  zip varchar(1024),
  country varchar(1024),
  phone varchar(1024) null,
  phone_ext varchar(1024) null,
  fax varchar(1024) null,
  fax_ext varchar(1024) null,
  email varchar(1024),
  unique NULLS NOT DISTINCT (street,zip,phone,email)
);

create table whois_nfo (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, domain varchar(255) unique, created timestamp with time zone null, updated timestamp with time zone null, registrant integer references whois_contact(id), admin integer references whois_contact(id), tech integer references whois_contact(id));
