CREATE OR REPLACE FUNCTION check_email(email text) RETURNS bool
LANGUAGE plperlu
AS $$
use Email::Address;

my @addresses = Email::Address->parse($_[0]);
return scalar(@addresses) > 0 ? 1 : 0;
$$;


CREATE TABLE public.track_email (
    uuid uuid PRIMARY KEY DEFAULT public.uuid_generate_v4() NOT NULL,
    email character varying(255) CONSTRAINT proper_email CHECK (check_email(email)),
    name varchar,
    website character varying(2000),
    subject varchar,
    content_url character varying(2000),
    pending timestamp with time zone,
    sent timestamp with time zone,
    constraint pkey_track_uniq unique(email,content_url)
);

create table public.track_email_clicks (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email_uuid uuid references track_email(uuid),
  tag varchar,
  clicked timestamp with time zone default now(),
  constraint ukey_uuid_tag unique(email_uuid,tag)
);

