--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8
-- Dumped by pg_dump version 16.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: whois_servers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.whois_servers (
    id integer NOT NULL,
    url character varying(255)
);


ALTER TABLE public.whois_servers OWNER TO postgres;

--
-- Name: whois_servers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.whois_servers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.whois_servers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: whois_servers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.whois_servers (id, url) FROM stdin;
1	whois.corporatedomains.com
5	whois.brandsight.com
7	whois.godaddy.com
9	whois.crsnic.net
10	whois.markmonitor.com
41	whois.squarespace.domains
45	whois.wildwestdomains.com
46	whois.networksolutions.com
47	whois.domain.com
49	whois.registrar.amazon
55	whois.ionos.com
56	whois.launchpad.com
57	whois.pir.org
68	whois.tucows.com
71	whois.nic.co
73	whois.biz
78	whois.register.com
79	whois.fastdomain.com
80	whois.webcentralgroup.com.au
84	whois.enom.com
90	whois.namesilo.com
92	whois.registrarsafe.com
125	whois.namecheap.com
126	whois.srsplus.com
145	whois.comlaude.com
261	whois.name.com
263	whois.lexsynergy.com
266	whois.discount-domain.com
292	whois.namejuice.com
367	whois.rrpproxy.net
368	whois.directnic.com
407	whois.registrar.amazon.com
445	whois.bluerazor.com
543	whois.wix.com
784	whois.nic.vet
802	whois.donuts.co
1250	whois.dotgov.gov
1559	whois.educause.edu
1718	whois.nic.us
1793	whois.easydns.com
2310	grs-whois.hichina.com
2448	whois.liquidnetlimited.co.uk
3072	whois.gochinadomains.com
3114	whois.publicdomainregistry.com
3231	whois.cloudflare.com
3245	whois.norid.no
3280	whois.namebright.com
3281	whois.domaindiscover.com
3285	whois.dreamhost.com
3288	whois.nominalia.com
3297	whois.nic.gov
3302	whois.gkg.net
3323	whois.eenet.ee
3334	whois.above.com
3354	whois.names4ever.com
3378	whois.namerider.com
3452	whois.web.com
3458	whois.dynadot.com
3467	whois.101domain.com
3515	whois.nic.me
3530	whois.nic.it
3637	whois.internet.bs
3709	whois.hostinger.com
3725	whois.scip.es
3729	whois.pairdomains.com
3730	whois.nic.io
3757	whois.gname.com
3877	whois.spaceship.com
3889	whois.omnis.com
3992	whois.no-ip.com
4008	whois.safenames.net
4013	whois.domainpeople.com
4082	whois.misk.com
4090	whois.sawbuck.com
4136	whois.ca.fury.ca
4227	whois.onlinenic.com
4282	whois.registrar.internetx.com
4301	whois.1api.net
4305	whois.jprs.jp
4324	whois.register4less.com
4377	whois.gocanadadomains.com
4406	whois.registermatrix.com
4529	whois.one.com
4610	whois.danesconames.com
4676	whois.twnic.net
4726	whois-service.virtualcloud.co
4820	whois.bigrock.com
4857	whois.nicline.com
4967	whois.joker.com
4983	whois.moniker.com
5169	whois.gofrancedomains.com
5197	whois.yoursrs.com
5308	whois.syrahost.com
5371	whois.corehub.net
5407	whois.rebel.com
5433	whois.nic.at
5545	whois.ovh.com
5551	grs-whois.aliyun.com
5582	whois.newfrontier.domains
5784	whois.pananames.com
5789	whois.domainit.com
6030	whois2.domain.com
6033	whois.nic.ru
6087	whois.opensrs.net
6142	whois.nic.bar
6209	whois.alpinedomains.com
6243	whois.nic.uk
6298	whois.lanic.la
6306	whois.domainregistry.com
6454	whois.uniregistrar.com
6877	whois.namescout.com
7038	whois.corsearch.domains
7067	whois.register.it
7086	whois.webnames.ca
7184	whois.meshdigital.com
7230	whois.netistrar.com
7284	whois.nic.travel
7306	whois.auda.org.au
7321	whois.advancedregistrar.com
7408	whois.aitdomains.com
7461	whois.akky.mx
7466	whois.west.cn
7532	whois.barbero.co.uk
7612	whois.iana.org
7931	whois.cira.ca
7961	whois.123-reg.co.uk
8052	whois.encirca.com
8407	whois.007names.com
8463	whois.nic.bank
8655	whois.nic.tl
8708	whois.epik.com
8796	whois.fabulous.com
8875	whois.tldregistrarsolutions.com
9251	whois.nic.gl
9460	whois.hosting.kr
9484	whois.nic.cc
9546	whois.registrar.eu
9806	whois.hoster.by
10053	whois.ukrnames.com
10054	whois.net-chinese.com.tw
10124	whois.inames.co.kr
10129	whois.whois.co.kr
10133	whois.nic.xyz
10424	whois.goaustraliadomains.com
10934	whois.nic.top
10951	whois.uniregistrar.net
11077	whois.dinahosting.com
11237	whois.domainsite.com
11953	whois.webhero.com
12076	whois.namesrs.com
12264	whois.ename.com
12489	whois.synergywholesale.com
12659	whois.nic.pro
12910	whois.domaincontext.com
12948	whois.lws.net
13087	whois.nic.online
13092	whois.nic.md
13637	whois.abion.com
13912	whois.eranet.com
14033	whois.afilias.net
14130	whois.webmasters.com
14137	whois.netim.com
15036	whois.nicenic.net
15188	whois.namecamp.com
15315	whois.infomaniak.com
16277	whois.regtime.net
16359	whois.nic.shop
16383	whois.antagus.de
16948	whois.instra.net
17310	whois.nic.site
17378	whois.annulet.com
17419	whois.eu
17527	whois.gomontenegrodomains.com
18687	whois.metaregistrar.com
18844	whois.star-domain.jp
18952	whois.dynadot3.com
18958	whois.tracer.ai
19351	whois.worldsite.ws
20019	whois.nameshield.net
21039	whois.enterprice.net
21173	whois.dynadot11.com
21213	whois.namebay.com
21659	whois.nic.tr
21661	whois.dynadot17.com
21791	whois.edomains.com
21796	whois.55hl.com
22360	whois.registrygate.com
22745	whois.denic.de
22847	whois.ledl.net
22919	grs-whois.kouming.com
23180	whois.nic.ar
23666	whois.nic.inc
23718	whois.diymysite.com
24220	whois.todaynic.com
24819	whois.dnspod.com
25081	who-is.whogohost.com
25169	whois.imena.ua
25718	whois.dotearth.com
25727	whois.turkticaret.net
25781	whois.acens.net
25962	whois.ownregistrar.com
26293	whois.72dns.com
26456	whois.beget.com
26491	whois.cosmotown.com
26850	whois.registry.in
26920	whois.webnic.cc
27438	whois.nic.ve
27792	whois.bookmyname.com
28139	whois.iaregistry.com
28356	whois.cdmon.com
28475	whois.nicproxy.com
28658	whois.domains.co.za
28687	whois.nic.best
29793	whois.nic.website
30313	whoisserver.inet.vn
30368	whois.ascio.com
31967	whois.nic.ch
32184	whois.nic.cloud
32390	whois.whc.ca
32969	whois.dynadot8.com
33631	whois.nic.attorney
34148	whois.dynadot9.com
34350	whois.nic.za
34549	whois.puredomain.com
35045	whois.dynadot15.com
35114	whois.tool.domains
35317	whois.gdntcl.com
35550	whois.donweb.com
36365	whois.domainnameblvd.com
37073	whois.udag.net
37229	whois.world4you.com
37372	whois.domains.coop
37704	whois.eurodns.com
38497	whois.nic.or.kr
39157	whois.paycenter.com.cn
39743	whois.neubox.com
39880	whois.netart-registrar.com
39949	whois.mx
41347	whois.in2net.com
41757	whois.pandi.or.id
43032	whois.rotld.ro
43230	whois.mijninternetoplossing.nl
43232	whois.nordnet.net
44066	whois.nic.tech
45337	whois.dynadot6.com
45860	whois.iis.se
46635	whois.metunic.com.tr
49870	www.whois.oxygen.nyc
50276	whois.reg.com
50544	whois.domainspot.com
50601	whois.easyspace.com
50745	whois.regtons.com
52316	ver.whois.matbao.net
52450	whois.dynadot14.com
55191	whois.ksdom.kr
56129	whois.profilebuilder.com
57605	whois.your-server.de
58117	whois.inleed.se
58273	whois.nic.tokyo
58892	whois.domainadministration.com
58992	whois.nicco.com
59005	whois.ripn.net
59427	whois.entorno.com
60194	grs-whois.cndns.com
60303	whois.isnic.is
61383	whois.domainipr.net
61461	whois.nic.br
62207	whois.domrobot.com
65383	whois.nic.es
67206	whois.enguard.com
67242	whois.35.com
68234	whois.bizcn.com
69762	whois.nic.moda
70054	whois.neen.it
70530	whois.mainreg.com
70674	whois.doregi.com
71071	whois.nic.store
73166	whois.safebrands.com
73911	whois.kenic.or.ke
74590	whois.registrarsec.com
76122	whois.hkirc.hk
76286	whois.nicnames.com
80465	whois.totalregistrations.com
80652	whois.com.ua
80790	whois.cronon.net
82003	whois.azprivatez.com
82983	whois.dynadot4.com
84033	whois.strangedomains.com
84151	whois.seo.domains
85289	whois.ihs.com.tr
85681	whois.nic.club
88689	whois.dns.be
89158	whois.register.ca
89801	whois.nic.design
92962	whois.ilovewww.com
93588	whois.dynadot13.com
94036	whois.psi-usa.info
94116	whois.domaininfo.com
94527	whois.nic.mortgage
95674	whois.yellowstart.com
95926	whois.dotalliance.com
96109	whois.nic.coop
99115	whois.1198.cn
102805	whois.afilias-srs.net
103004	whois.dynadot16.com
103718	whois.nawang.cn
104171	whois.brandcloud.cn
105902	whois.globaldomaingroup.com
107172	iwhois.webnic.cc
107239	whois.nic.abb
110634	whois.dynu.com
110765	whois.register.bg
112828	whois.resellercamp.com
112841	whois.quedomain.com
113257	whois.isoc.org.il
116037	whois.register.eu
116232	whois.domainregistry.ie
116234	whois.website.ws
116479	whois.genious.net
116687	whois.saudinic.net.sa
116799	whois.nic.law
117895	whois.gonbei.jp
118290	whois.vertexnames.com
120656	whois.alantron.com
122808	whois.tnet.hk
124087	whois.nic.fr
128738	whois.rebel.ca
130273	whois.domainnameshop.com
133008	whois.authenticweb.com
135768	whois-generic.marcaria.com
135795	whois.hkdns.hk
136926	whois.weare.ie
137340	whois.nic.cl
138277	whois.centralnic.com
140765	whois.dns.pl
141270	whois.hknic.net.hk
141459	whois.nic.ms
141854	whois.nic.health
144329	whois.dynadot10.com
144940	whois.domain-registry.nl
145231	whois.nic.tv
145475	whois.nic.name
145996	whois.promopeople.com
146025	whois.nic.faith
146680	whois.nic.love
147456	whois.nic.cyou
148801	whois.dynadot5.com
150130	whois.srs.net.nz
151014	whois.libris.com
156776	whois.psi.jp
159811	whois.nic.nyc
160338	whois.apiname.com
161381	whois.arnes.si
165652	whois.nic.miami
165682	whois.channelisles.net
167156	whois.ssandomain.com
169294	whois.amnic.net
174737	whois.tecnocratica.net
174948	whois.nic.social
177693	whois.alohanic.com
179849	whois.namespro.ca
181849	whois.ukraine.com.ua
182747	whois.nic.re
183182	whois.uniregistry.net
183286	whois.papaki.gr
186047	whois.dynadot7.com
191376	whois.domainclub.com
195814	whois.nic.garden
205460	216.117.191.5
206646	whois.salestrar.com
206720	whois.nic.rehab
212808	whois.dotname.co.kr
219078	whois.global-village.de
227308	whois.nic.lv
229957	whois.nic.li
230806	whois.nic.build
240274	whois.zzy.cn
242447	whois.r01.ru
244614	whois.fiducia.com
244651	whois.nic.vip
245188	whois.nic.dentist
246119	whois.nic.rocks
248720	whois.serverplan.com
251689	whois.nic.ac
252313	whois.nic.fun
253429	whois.registry.net.za
256264	whois.aerotek.com.tr
261064	whois.nic.pub
261609	whois.secura-gmbh.de
265708	whois.nominate.net
265914	whois.nic.lawyer
266367	whois.pavietnam.vn
266793	whois.vm.com
273907	whois.nic.fit
275934	whois.web4africa.net
277760	whois.nic.work
280993	whois.nic.host
282355	whois.netcom.cm
286589	whois.ccdomain.co.kr
288819	whois.julyname.com
292650	whois.gzidc.com
297491	whois.nic.cz
298249	whois.nic.stream
298312	whois.nic.st
304853	rdap.juming.com
306837	whois.nic.ci
309355	whois.blacknight.com
316425	whois.dotology.com
321806	whois.mynic.my
323402	whois.securebackorder.com
325830	whois.identitydigital.services
326622	whois.nic.ink
326890	whois.hostnameservices.net
329619	whois.dynadot12.com
331701	whois.registro.br
341174	whois.twt.it
347244	whois.nic.ai
350870	whois.rumahweb.com
352961	whois.interdominios.com
354200	whois.nic.ht
363277	whois.magic.fr
371736	rdap.gonbei.jp
376639	whois.namepal.com
380365	whois.domainshype.com
382357	whois.cnnic.net.cn
394088	whois.aero
400277	whois.nic.pw
400452	whois.sfn.cn
402006	whois.nic.skin
410737	whois.nic.tc
412560	whois.nhanhoa.com
415475	whois.nic.rodeo
418688	whois.nic.gop
422661	whois.hostingireland.ie
423997	whois.nic.market
433451	whois.nic.art
434469	whois.webair.com
434939	whois.cyandomains.com
447183	whois.loading.es
451385	whois.costrar.com
471860	whois.nic.beer
471913	wedominios.webempresa.eu
482695	www.safenames.net
490625	whois.nic.menu
504918	whois.nic.yoga
507969	whois.sk-nic.sk
512980	whois.twnic.net.tw
519968	whois.namware.com
524426	whois.nameperfections.com
528857	whois.name.net
528896	whois.nic.bo
529970	whois.ibi.net
535155	domains.meshdigital.com
543749	whois.suempresa.com
548336	whois.nic.hu
550289	whois.vodien.com
555484	whois.namebeacon.com
555745	whois.namespace.au
556506	whois.boterosolutions.net
577785	whois.cps-datensysteme.de
584999	whois.gandi.net
587600	whois.zhuoyue.wang
599044	whois.nic.fm
603681	rdap.routing.net
605129	whois.17domain.com
610945	whois.magicfriday.com
630207	whois.gatewaysrs.com
640350	whois.aeda.net.ae
662061	whois.jumi.com
692435	whois.nic.bm
695761	whois.findgooddomains.com
698599	whois.theregistrarcompany.com
705733	whois.ireg.net
720103	whois.nic.one
747193	whois.thnic.co.th
747651	kero.yachay.pe
755802	whois.rockenstein.de
776573	whois.systonic.fr
777672	whois.ripe.net
784030	whois.digivity.com
790942	whois.purpleit.com
793185	whois.anchovy.com
801055	whois.tznic.or.tz
804991	whois.upperlink.ng
855376	whois.dotarai.com
863586	whois.azdomainz.com
867475	whois.nic.global
881416	whois.ja.net
889160	whois.domaintegrity.com
892238	whois.nic.cpa
899282	whois.matbao.net
899872	whois.oleane.net
916801	whois.tuonome.com
921827	whois.nic.kw
940881	whois.tucowsregistry.net
942137	whois.zenregistry.com
944279	whois.tirupatidomains.in
950866	whois.nic.do
951182	whois.rnids.rs
967511	whois.isimtescil.net
971327	whois.ficora.fi
974465	whois.iam.net.ma
988491	whois.zohodomains.com
998769	whois.domaincostclub.com
1007986	whois.nic.as
1024764	whois.domus.com
1026926	whois.hupo.com
1043049	www.onlinenic.com
1071815	whois.nic.kz
1085550	whois.domtake.com
1106367	whois.nic.la
1130159	whois.nic.ae
1136288	whois.dk-hostmaster.dk
1172695	whois.nic.space
1188231	whois.oray.com
1207165	whois.nic.barclays
1207585	whois.nic.beauty
1213712	whois.nic.cx
1220406	whois.nic.rest
1228154	whois.kagoya.net
1238321	whois.nic.softbank
1270034	whois1.nic.bi
1283738	whois.nic.ge
1294098	whois.regne.net
1296715	whois.namesecure.com
1299977	whois.nic.gs
1345525	whois.costdomain.com
1347947	whois.registry.om
1353265	whois.instantdomains.com
1371423	whois.nic.im
1386938	whois.jumboname.com
1388449	whois.ddd.com
1396251	whois.publicinterestregistry.net
1404959	whois.nic.net.ng
1428619	whois.8hy.cn
1432564	whois.domainnamefwy.com
1440021	whois.do-reg.jp
1452241	whois.co.kr
1460523	ewhois.sundns.com
1464280	whois.nametofame.com
1480721	whois.nic.haus
1506755	whois.nic.ly
1516608	whois.dns.pt
1519865	whois.nic.insurance
\.


--
-- Name: whois_servers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.whois_servers_id_seq', 1547354, true);


--
-- Name: whois_servers whois_servers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.whois_servers
    ADD CONSTRAINT whois_servers_pkey PRIMARY KEY (id);


--
-- Name: whois_servers whois_servers_url_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.whois_servers
    ADD CONSTRAINT whois_servers_url_key UNIQUE (url);


--
-- PostgreSQL database dump complete
--

