--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8
-- Dumped by pg_dump version 16.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: pending_yp; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pending_yp (
    url character varying(2000) NOT NULL,
    resolved timestamp with time zone,
    status integer
);


ALTER TABLE public.pending_yp OWNER TO postgres;

--
-- Name: yellow_pages_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.yellow_pages_categories (
    id integer NOT NULL,
    category character varying(255)
);


ALTER TABLE public.yellow_pages_categories OWNER TO postgres;

--
-- Name: yellow_pages_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.yellow_pages_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.yellow_pages_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: yellow_pages_citycat; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.yellow_pages_citycat (
    id integer NOT NULL,
    url character varying(2000)
);


ALTER TABLE public.yellow_pages_citycat OWNER TO postgres;

--
-- Name: yellow_pages_citycat_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.yellow_pages_citycat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.yellow_pages_citycat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: yellow_pages_loading; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.yellow_pages_loading (
    id integer NOT NULL,
    address character varying(255),
    city character varying(80),
    name character varying(255),
    phone character varying(255),
    state character varying(2),
    tags character varying(255),
    website character varying(2000),
    zip character varying(11),
    category character varying(255)
);


ALTER TABLE public.yellow_pages_loading OWNER TO postgres;

--
-- Name: yellow_pages_loading_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.yellow_pages_loading ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.yellow_pages_loading_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pending_yp pending_yp_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pending_yp
    ADD CONSTRAINT pending_yp_pkey PRIMARY KEY (url);


--
-- Name: yellow_pages_categories yellow_pages_categories_category_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.yellow_pages_categories
    ADD CONSTRAINT yellow_pages_categories_category_key UNIQUE (category);


--
-- Name: yellow_pages_categories yellow_pages_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.yellow_pages_categories
    ADD CONSTRAINT yellow_pages_categories_pkey PRIMARY KEY (id);


--
-- Name: yellow_pages_citycat yellow_pages_citycat_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.yellow_pages_citycat
    ADD CONSTRAINT yellow_pages_citycat_pkey PRIMARY KEY (id);


--
-- Name: yellow_pages_citycat yellow_pages_citycat_url_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.yellow_pages_citycat
    ADD CONSTRAINT yellow_pages_citycat_url_key UNIQUE (url);


--
-- Name: yellow_pages_loading yellow_pages_loading_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.yellow_pages_loading
    ADD CONSTRAINT yellow_pages_loading_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

