--
-- Yellow Pages crawler schema
--
-- Idempotent version of the pg_dump previously checked in here.
-- Safe to run against a fresh database or one that already has some/all
-- of these objects — every statement is guarded with IF NOT EXISTS.
--
-- Covers the tables used by parsers/yellow_pages.pl and monitored by
-- parsers/stats_yp.pl. See parsers/YELLOWPAGES.md for how each column is
-- populated and the pipeline these tables feed.
--
-- All four tables live in the yellow_pages schema (not public). Callers
-- must schema-qualify references or `SET search_path` to include
-- yellow_pages.
--
-- NOT covered here: the curated yp.yellow_pages promotion table and its
-- public.domain dependency, defined in etc/tables.sql. That promotion
-- step is manual (see etc/scratch.sql) and out of scope for the crawler
-- schema.
--

CREATE SCHEMA IF NOT EXISTS yellow_pages;

--
-- pending_yp: crawl queue. One row per URL to fetch.
--
-- host was added to parsers/yellow_pages.pl on 2025-07-12 (sharding the
-- queue across crawler boxes) but was missing from the original dump of
-- this file, which predates that change. It's included here, plus the
-- partial index the worker's claim query (`where resolved is null and
-- host = ?`) needs to stay fast as the table grows.
--
CREATE TABLE IF NOT EXISTS yellow_pages.pending_yp (
    url      character varying(2000) NOT NULL,
    resolved timestamp with time zone,      -- NULL = not yet fetched
    status   integer,                       -- HTTP status; only 200/404 are ever recorded
    host     character varying(255),        -- hostname() of the worker this URL is sharded to
    CONSTRAINT pending_yp_pkey PRIMARY KEY (url)
);

-- in case an existing table predates the host column
ALTER TABLE yellow_pages.pending_yp ADD COLUMN IF NOT EXISTS host character varying(255);

CREATE INDEX IF NOT EXISTS pending_yp_claim_idx
    ON yellow_pages.pending_yp (host)
    WHERE resolved IS NULL;

--
-- yellow_pages_categories: categories discovered from
-- https://www.yellowpages.com/categories
--
-- status/fetched record the outcome of bootstrap Step 2's per-category fetch.
-- Without them there is no record anywhere of which categories failed: the
-- generic failure path in send_url() updates pending_yp, but bootstrap's
-- category URLs are never inserted there, so that UPDATE matches zero rows
-- and the failure is silently lost. --retry-failures reads these columns.
CREATE TABLE IF NOT EXISTS yellow_pages.yellow_pages_categories (
    id       integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    category character varying(255),
    status   integer,                          -- HTTP status of the last category fetch
    fetched  timestamp with time zone,         -- NULL = never attempted
    CONSTRAINT yellow_pages_categories_pkey PRIMARY KEY (id),
    CONSTRAINT yellow_pages_categories_category_key UNIQUE (category)
);

-- in case an existing table predates the retry-tracking columns
ALTER TABLE yellow_pages.yellow_pages_categories ADD COLUMN IF NOT EXISTS status integer;
ALTER TABLE yellow_pages.yellow_pages_categories ADD COLUMN IF NOT EXISTS fetched timestamp with time zone;

-- --retry-failures selects on (fetched is null or status <> 200)
CREATE INDEX IF NOT EXISTS yellow_pages_categories_retry_idx
    ON yellow_pages.yellow_pages_categories (status)
    WHERE fetched IS NULL OR status <> 200;

--
-- yellow_pages_citycat: per-city category listing paths discovered from
-- https://www.yellowpages.com/categories/<category>
-- e.g. /los-angeles-ca/plumbers
--
CREATE TABLE IF NOT EXISTS yellow_pages.yellow_pages_citycat (
    id  integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    url character varying(2000),
    CONSTRAINT yellow_pages_citycat_pkey PRIMARY KEY (id),
    CONSTRAINT yellow_pages_citycat_url_key UNIQUE (url)
);

--
-- yellow_pages_loading: raw scrape landing zone. No uniqueness constraint
-- on purpose — the worker's INSERT has no ON CONFLICT, so re-crawling a
-- listing page duplicates rows here; de-duplicate on promotion to
-- yp.yellow_pages.
--
-- address falls back to the literal sentinel '123 Anystreet, HV' when the
-- listing has no parseable street-address/adr element — filter that out
-- downstream rather than treating it as a real address.
--
CREATE TABLE IF NOT EXISTS yellow_pages.yellow_pages_loading (
    id       integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    address  character varying(255),
    city     character varying(80),
    name     character varying(255),
    phone    character varying(255),
    state    character varying(2),
    tags     character varying(255),
    website  character varying(2000),
    zip      character varying(11),
    category character varying(255),
    CONSTRAINT yellow_pages_loading_pkey PRIMARY KEY (id)
);
