package Quotes;
use Moose;
use List::Util qw/shuffle/;

has 'quotes' => ( is => "rw", isa => "Any", default => sub {
        my @q = (
'"I am not afraid. I was born to do this." —Joan of Arc',
'"You’ll seldom experience regret for anything that you’ve done. It is what you haven’t done that will torment you." —Wayne Dyer',
'"Anything I’ve ever done that ultimately was worthwhile…initially scared me to death." —Betty Bender',
'"You must do the thing which you think you cannot do." —Eleanor Roosevelt',
'"Many people are afraid of the dark, but the real tragedy is those who are afraid of the light." —Unknown',
'"I have loved the stars too fondly to be fearful of the night." —Galileo Galilei',
'"The only time you run out of chances is when you stop taking them." —Unknown',
'"In order to dominate the soul you must also learn to dominate the body. And in order to dominate the body you cannot fear pain." —Paulo Coelho',
'"Every shadow—no matter how deep—is threatened by morning light." —Unknown',
'"As a rule, men worry more about what they can’t see than about what they can." —Julius Caesar',
'"Anxiety is just repeatedly experiencing failure in advance." —Seth Godin',
'"By acting bravely we become brave; not the other way round." —Unknown',
'"Forgiveness is choosing to love. It is the first skill of self-giving love." —Gandhi',
'"Forgiveness is the fragrance the violet sheds on the heel that has crushed it.” —Mark Twain',
'"An eye for eye only ends up making the whole world blind." —Ghandi',
'"The only people with whom you should try to get even are those who have helped you." —John E. Southard',
'"The weak can never forgive. Forgiveness is the attribute of the strong.” —Ghandi',
'"When I choose to imagine someone’s pain/perspective I lose my appetite for anger." —Unknown',
'"Sometimes your joy is the source of your smile, but sometimes your smile can be the source of your joy." —Thich Nhat Hanh',
'"The only reason you are happy is because you choose to be happy. Happiness is a choice, and so is suffering." —don Miguel Ruiz',
'"Identify your problems but give your power and energy to solutions." —Tony Robbins',
'"Positive people don’t need an outside push; they seemingly have a natural internal push that continually pulls them forward." —Unknown',
'"You must choose between your attachments and happiness." —Adyashanti',
'"Happy are those who dream dreams and are ready to pay the price to make them come true." —Unknown',
'"The pessimist complains about the wind; the optimist expects it to change; the realist adjusts the sails." —William A. Ward',
'"Not only is the kingdom of heaven within, but the kingdom of Hell is within as well – it’s your choice." —Unknown',
'"What we feel is not based on our experience, but on our INTERPRETATION of experiences." —Anthony Robbins',
'"In every life we have some trouble, but when you worry you make it double. Don’t worry. Be happy." —Bobby McFerrin',
'"The sanest thing in this world is love." —Anne Sexton',
'"The hunger for love is much more difficult to remove than the hunger for bread." —Mother Teresa',
'"When two people fall in love, past and future disappear." —The Alchemist',
'"Love means protection, adoration, mutual growth, & respect above all other things. Without this, love is an illusion, a confused attachment." —Dena Botbyl',
'"Love is the beginning of the journey, its end, and the journey itself." —Unknown',
'"Detachment is not indifference. Detachment is love without expecting anything in return." —Unknown',
'"There is only love; there is nothing else." —Dena Botbyl',
'"When I work fourteen hours a day, seven days a week, I get lucky." —Armand Hammer',
'"Opportunities multiply as they are seized." —Sun Tsu',
'"The most important thing about art is to work. Nothing else matters except sitting down every day and trying." —Steven Pressfield',
'"It’s not what we do once in a while that shapes our lives, but what we do consistently." —Anthony Robbins',
'"Everyone wants to be strong and self sufficient, but few are willing to put in the work necessary to achieve worthy goals." —Gandhi',
'"Not failure, but low aim, is the crime. In great attempts it is glorious even to fail." —Bruce Lee',
'"When the lion is chasing the antelope, he doesn’t look back. He has to eat." —Robert Cheruiyot',
'"Do what you can, where you are, with what you have." —Theodore Roosevelt',
'"The Pearl Principle – no inner irritation, no pearl." —Lama Surya Das',
'"Discipline is an exercise of repetition. Not once or twice but until. Until completed." —Unknown',
'"Giving up is not failing — it’s the chance to begin again." —Unknown',
'"We only get to play this game one time, one life." —Gary Vaynerchuk',
'"If people only knew how hard I work to gain my mastery, it wouldn’t seem so wonderful at all." —Michelangelo',
'"If you’re bored with life, if you don’t get up every morning with a burning desire to do things – you don’t have enough goals." —Lou Holtz',
'"Ask not what the world needs; ask what makes you come alive, and then go and do that. Because what the world needs is people who have come alive." —Howard Thurman',
'"We are not here merely to make a living. We are here to enrich the world." —Woodrow Wilson',
'"Whether you KNOW it or not, ACCEPT it or not, with each moment that passes, you get closer to fulfilling your life’s purpose." —Dena Botbyl',
'"A bird doesn’t sing because it has an answer, it sings because it has a song." —Lou Holtz',
'"Let go and let God." —Unknown',
'"God long ago drew a circle in the sand exactly around the spot where you are standing right now. You were never not coming here." —Sufi poem',
'"Remember that when you truly want something, the entire Universe conspires to make it happen." —The Alchemist',
'"There will come a time when you believe everything is finished. That will be the beginning." —Louis L’Amour',
'"Act, & God will act." —Joan of Arc',
'"When you let go of the need for any and all outcomes life becomes a creative magical adventure." —Deepak Chopra',
'"To me faith means not worrying." —John Dewey',
'"Whatever is… is best." —Ella Wheeler Wilcox',
'"Hold fast to dreams, for if dreams die, life is a broken winged bird that cannot fly." —Langston Hughes',
'"The present moment is the still point around which the universe arises and subsides, only to be reborn again, fresh as a new born child." —Deepak Chopra',
'"With the past, I have nothing to do; nor with the future. I live now." —Ralph Waldo Emerson',
'"Begin at once to live, and count each day as a separate life." —Seneca',
'"Time is free, but it’s priceless. You can’t own it, but you can use it. Once you’ve lost it you can never get it back." —Harvey MacKay',
'"Never grow a wishbone, daughter, where your backbone ought to be." —Clementine Paddleford',
'"Whatever I fight weakens me. Whatever I cooperate with strengthens me." —Wayne Dyer',
'"There is one grand lie: that we are limited. The only limits we have are the limits we believe." —Wayne Dyer',
'"The people you have to lie to, own you. The things you have to lie about, own you." —Michael Ventura',
'"I count him braver who overcomes his desires than him who conquers his enemies; for the hardest victory is over self." —Aristotle',
'"The big question is whether you are going to be able to say a hearty yes to your adventure." —Joseph Campbell',
'"Be willing to say to those in your charge, “I don’t know.” —Unknown',
'"There are three ways to lead: 1. By example 2. By example 3. By example." —Unknown',
'"As we are liberated from our own fear, our presence actually liberates others." —Marianne Williamson',
'"Many people have gone a lot farther than they thought they could because someone else thought they could." —Zig Ziglar',
'"A bird in a cage is safe but God didn’t create birds for that." —Unknown',
'"Nature goes to the same place to create a galaxy of stars: a cluster of nebulas, a rain forest, a human body, or a thought. That place is Spirit." —Deepak Chopra',
'"Life begets life. Energy creates energy. It is by spending oneself that one becomes rich." —Sarah Bernhardt',
'"The mind is its own place, and in itself can make a heaven of hell, a hell of heaven." —John Milton',
'"If the only prayer you said in your whole life was, “Thank You,” that would suffice." —Meister Eckhart',
'"There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is." —Albert Einstein',
'"In the right light, at the right time, everything is extraordinary." —Aaron Rose',
'"Out beyond ideas of wrongdoing and rightdoing, there is a field. I will meet you there." —Rumi',
'"Be kind, for everyone you meet is fighting a hard battle." —Plato',
'"Your own soul is nourished when you are kind; it is destroyed when you are cruel." —King Solomon',
'"Don’t allow your wounds to turn you into a person you are not." —Paulo Coelho',
'"My every thought has the power either to wound or heal. I will use my thoughts wisely and respect their power." —Deepak Chopra',
'"Before you speak, ask yourself: is it kind, is it necessary, is it true, does it improve on the silence? —Unknown',
'"We are never so much disposed to quarrel with others as when we are dissatisfied with ourselves." —William Hazlitt',
'"All the pain of a human life is caused by words, as is all the joy." —Yogic sages',
'"The most I can do for my friend is simply be his friend." —Henry David Thoreau',
'"You must give up the life you planned in order to have the life that is waiting for you." —Joseph Campbell',
'"Learning to unlearn is the highest form of learning." —Buddhist proverb',
'"Every great mistake has a half way moment, a split second when it can be recalled and perhaps remedied." —Pearl Buck',
'"Facts do not cease to exist because they are ignored." —Aldous Huxley',
'"Thousands of geniuses live and die undiscovered – either by themselves or by others." —Mark Twain',
'"Every human is an artist. And this is the main art that we have: the creation of our story." —don Miguel Ruiz',
'"The definition of insanity is doing the same thing over and over again and expecting different results." —Albert Einstein',
'"First they ignore you, then they laugh at you, then they fight you, then you win." —Ghandi',
'"Having the fewest wants, I am nearest to the gods." —Socrates',
);
return \@q;
});

sub randomQuote {
    my $s = shift;
    my @quotes = shuffle(@{ $s->quotes });


    return shift @quotes;
}

1;
